feat: add exit codes handling

diff --git a/.github/workflows/filter-pr-mutants.yml b/.github/workflows/filter-pr-mutants.yml
--- a/.github/workflows/filter-pr-mutants.yml
+++ b/.github/workflows/filter-pr-mutants.yml
@@ -58,7 +58,35 @@ jobs:
             done
           done
 
-      - name: Print mutants
+          for folder in "${folders[@]}"; do
+            exit_code=$(<"${folder}/exit_code.txt")
+            most_relevant_exit_code=0
+
+            case $exit_code in
+            4)
+                most_relevant_exit_code=4
+                ;;
+            1)
+                [ "$most_relevant_exit_code" -eq 0 ] && most_relevant_exit_code=1
+                ;;
+            2)
+                [ "$most_relevant_exit_code" -eq 0 ] && most_relevant_exit_code=2
+                ;;
+            3)
+                [ "$most_relevant_exit_code" -eq 0 ] && most_relevant_exit_code=3
+                ;;
+            0)
+                ;;
+            *)
+                echo "Unknown exit code $exit_code"
+                most_relevant_exit_code=$exit_code
+                ;;
+            esac
+          done
+
+          echo "$most_relevant_exit_code" > './mutants-shards/exit_code.txt'
+
+      - name: Print mutants and handle exit codes
         run: |
           if [ -s ./mutants-shards/missed.txt ]; then
             echo "Found missed mutants:"
@@ -73,8 +101,37 @@ jobs:
             echo "-------------"
             echo "Found unviable mutants:"
             cat ./mutants-shards/unviable.txt
-            echo "-------------"
+            echo ""
             echo "To resolve this issue, consider one of the following options:"
             echo "1. Create 'Default::default()' implementation for the specific structure."
             echo "2. Add '#[mutants::skip]' or '#[cfg_attr(test, mutants::skip)]' function headers."
+            echo "-------------"
           fi
+
+          exit_code=$(<"mutants-shards/exit_code.txt")
+
+          case $exit_code in
+            0)
+                if [ -s ./mutants-shards/unviable.txt ]; then
+                  echo "Found unviable mutants!"
+                  exit 1
+                fi
+              echo "All new and updated functions are caught!"
+              ;;
+            1)
+              echo "Invalid command line arguments!"
+              exit 1
+              ;;
+            2 | 3)
+              echo "Found missed/timeout/unviable mutants!"
+              exit 1
+              ;;
+            4)
+              echo "Building the packages failed without any mutations!"
+              exit 1
+              ;;
+            *)
+              echo "Unknown exit code: $exit_code"
+              exit 1
+            ;;
+          esac
